### ISSUE TITLE
[TASK] Implement TokenWrapper Contract

### ISSUE THREAD

**Issue by dharjeezy** [webb-tools/protocol-ink#33]
You can check out how it is being implemented in [protocol-cosmwasm](https://github.com/webb-tools/protocol-cosmwasm/tree/main/contracts/tokenwrapper)

**Comment by dharjeezy** [comment]
So, I have been trying to hack on how to go about the wrap() contract function for the token wrapper contract.

I saw in [Solidity](https://github.com/webb-tools/protocol-solidity/blob/main/contracts/tokens/TokenWrapper.sol#L59) that there is actually this` address(0)` that is used to determine if a particular tokenAddress is a native token one(@nepoche explained this). 

And then on the cosmwasm end, I saw that there are two different wrap functions, the [wrap_native](https://github.com/webb-tools/protocol-cosmwasm/blob/main/contracts/tokenwrapper/src/contract.rs#L172) and the[wrap_cw20](https://github.com/webb-tools/protocol-cosmwasm/blob/main/contracts/tokenwrapper/src/contract.rs#L363). In the cosmwasm end, there is a check to filter the particular native token [here](https://github.com/webb-tools/protocol-cosmwasm/blob/main/contracts/tokenwrapper/src/contract.rs#L189)

I am curious as to how to represent/determine native token in the protocol-ink token wrapper contract, one suggestion I got from open brush is that since on the solidity end the ` address(0)` is like a marker for native token, we can decide to have our own marker on the protocol ink side, for instance, we can decide to use `Option<AccountId>`, if it is `None`, then we can say the tokenAddress is a native one. @drewstone  @shekohex  I want to know what you think about this?

**Comment by shekohex** [comment]
> we can decide to have our own marker on the protocol ink side, for instance, we can decide to use Option<AccountId>, if it is None, then we can say the tokenAddress is a native one.

I like this idea, looks good and is reasonable to implement.
