### ISSUE TITLE
[TASK] Integration test for getting amount to wrap and Identifying the units of psp22 token

### ISSUE THREAD

**Issue by dharjeezy** [webb-tools/protocol-ink#38]
In the Token wrapper contract, we need to do the following:

- [ ] Identify the normal units of the psp22 token
- [ ] Integration test for getting amount to wrap

**Comment by iTranscend** [comment]
Hi @dutterbutter and @dharjeezy, I see this issue is open. Can I take it up?

**Comment by dutterbutter** [comment]
Closed in #55
